version: '2'

services:
  db:
    container_name: db-ec021
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ec021
      MYSQL_USER: ec021
      MYSQL_PASSWORD: ec021
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: api-ec021
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src:/home/node/app/src
    environment:
      DB_URI: db
      DB_NAME: ec021
      DB_USER: ec021
      DB_PASSWORD: ec021
    depends_on:
      - db

  view:
    container_name: view-ec021
    build:
      context: .
      dockerfile: view.Dockerfile
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/home/node/public
