CREATE DATABASE IF NOT EXISTS ec021;
CREATE TABLE IF NOT EXISTS toddy (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lote` VARCHAR(50) NOT NULL,
  `conteudo` INT NOT NULL,
  `validade` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`)
);
